#!/usr/bin/env python3
"""Generate Hermes-native slash-command wrapper skills for mirrored Claude Code skills.

Claude remains source of truth under ~/.claude/skills. The symlink mirror under
~/.hermes/external-repos/claude-code-skills exposes the active Claude skills.
This script creates small Hermes skills under ~/.hermes/skills/claude-code/ so
Hermes can register /<skill-name> slash commands without copying Claude content.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import Any

import yaml

HOME = Path.home()
MIRROR = HOME / ".hermes" / "external-repos" / "claude-code-skills"
WRAPPERS = HOME / ".hermes" / "skills" / "claude-code"
CONFIG = HOME / ".hermes" / "config.yaml"
ARCHIVE = HOME / ".hermes" / "skills" / ".archive" / "claude-code-wrapper-conflicts"

# These are intentionally not exposed as Claude wrappers in Hermes.
EXCLUDE_NAMES = {"session-close", "remember-fact", "state-transfer"}
# Prefer Hermes-native implementations for these names.
HERMES_NATIVE_PREFERRED = {"codex", "humanizer"}


def parse_frontmatter(skill_md: Path) -> tuple[dict[str, Any], str]:
    text = skill_md.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw = text[3:end]
    body = text[text.find("\n", end + 4) + 1 :]
    try:
        fm = yaml.safe_load(raw) or {}
        if not isinstance(fm, dict):
            fm = {}
    except Exception:
        fm = {}
    return fm, body


def clean_description(desc: str, fallback: str) -> str:
    desc = " ".join((desc or "").split())
    if not desc:
        desc = f"Invoke Kevin's Claude Code `{fallback}` skill from the symlink mirror."
    # Hermes enforces <=1024 chars; keep wrappers comfortably below that.
    return desc[:900]


def wrapper_content(name: str, desc: str, source: Path) -> str:
    safe_source = str(source)
    title = name.replace("-", " ").title()
    return f"""---
name: {name}
description: {desc}
version: 1.0.0
author: Hermes Agent
license: MIT
metadata:
  hermes:
    tags: [claude-code, wrapper, slash-command]
    related_skills: [claude-code-skills]
---

# {title} Claude Code Skill Wrapper

## Purpose

This is a Hermes-native slash-command wrapper for Kevin's Claude Code skill `{name}`.
Claude remains the source of truth. This wrapper exists so Kevin can invoke the workflow in Hermes as:

```text
/{name} <task or target>
```

## Required behavior

When this skill is invoked:

1. Immediately read the source Claude skill:
   - `{safe_source}/SKILL.md`
2. Treat that Claude `SKILL.md` as the authoritative workflow for this task.
3. Follow the Claude skill exactly where compatible with Hermes tools and safety boundaries.
4. Preserve any user instruction supplied after `/{name}` as the task target.
5. If the Claude skill references supporting files under `references/`, `templates/`, `scripts/`, or `assets/`, resolve them relative to:
   - `{safe_source}`
6. Do not write to `/Users/kevin/.claude` unless Kevin explicitly asks. If the Claude skill includes memory/session-writing behavior, reinterpret it into Hermes-native memory or Hermes-owned files unless Kevin explicitly asks to update Claude state.

## Source of truth

- Claude skill directory: `{safe_source}`
- This wrapper is generated by: `/Users/kevin/.hermes/scripts/generate_claude_skill_wrappers.py`

## Verification

Before acting on the task, confirm the source skill was read successfully. If it cannot be read, stop and report the exact missing path.
"""


def iter_mirrored_skill_dirs() -> list[tuple[str, Path, str]]:
    out: list[tuple[str, Path, str]] = []
    for child in sorted(MIRROR.iterdir()):
        if child.name == "MANIFEST.md" or not child.is_dir():
            continue
        md = child / "SKILL.md"
        if not md.exists():
            continue
        fm, _ = parse_frontmatter(md)
        name = str(fm.get("name") or child.name).strip()[:64]
        if not name or name in EXCLUDE_NAMES or name in HERMES_NATIVE_PREFERRED:
            continue
        desc = clean_description(str(fm.get("description") or ""), name)
        out.append((name, child, desc))
    return out


def main() -> None:
    if not MIRROR.exists():
        raise SystemExit(f"Mirror not found: {MIRROR}")

    WRAPPERS.mkdir(parents=True, exist_ok=True)
    generated = iter_mirrored_skill_dirs()
    generated_names = {name for name, _, _ in generated}

    # Remove stale generated wrappers that no longer have a mirrored source.
    for existing in list(WRAPPERS.iterdir()):
        if not existing.is_dir():
            continue
        md = existing / "SKILL.md"
        if not md.exists():
            continue
        text = md.read_text(encoding="utf-8", errors="ignore")
        if "generate_claude_skill_wrappers.py" in text and existing.name not in generated_names:
            shutil.rmtree(existing)

    written = 0
    for name, source, desc in generated:
        target_dir = WRAPPERS / name
        target_dir.mkdir(parents=True, exist_ok=True)
        target = target_dir / "SKILL.md"
        content = wrapper_content(name, desc, source)
        if not target.exists() or target.read_text(encoding="utf-8", errors="ignore") != content:
            target.write_text(content, encoding="utf-8")
            written += 1

    cfg = yaml.safe_load(CONFIG.read_text(encoding="utf-8")) or {}
    skills = cfg.setdefault("skills", {})
    disabled = set(skills.get("disabled") or [])
    # Wrapper names must be enabled so Hermes registers /<skill-name> commands.
    # The mirrored external skills can stay in external_dirs; local wrappers scan first.
    disabled -= generated_names
    # Keep explicitly unsafe/duplicate names disabled.
    disabled.update(EXCLUDE_NAMES)
    disabled.add("humanizer")
    disabled.discard("codex")
    disabled.discard("session-close")
    skills["disabled"] = sorted(disabled)
    CONFIG.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")

    print(f"wrappers={len(generated)} written={written} dir={WRAPPERS}")
    print(f"enabled_wrapper_commands={len(generated_names)}")


if __name__ == "__main__":
    main()
